"""Download Valorant art assets (agents + competitive rank tiers) from valorant-api.com.

Deterministic: same source, same output. Re-run any time to refresh assets.

Usage:
    python scripts/fetch_valorant_assets.py

Writes:
    frontend/public/assets/agents/<slug>.png       agent display icons
    frontend/public/assets/ranks/<slug>.png        competitive tier icons
    frontend/lib/generated/valorant-assets.ts       name -> path manifest

valorant-api.com is a community API serving Riot's static assets. No auth needed.
"""

from __future__ import annotations

import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS_DIR = os.path.join(ROOT, "frontend", "public", "assets", "agents")
RANKS_DIR = os.path.join(ROOT, "frontend", "public", "assets", "ranks")
MANIFEST = os.path.join(ROOT, "frontend", "lib", "generated", "valorant-assets.ts")

API = "https://valorant-api.com/v1"


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def get_json(url: str) -> dict:
    with urllib.request.urlopen(url) as r:
        return json.loads(r.read())


def download(url: str, dest: str) -> None:
    with urllib.request.urlopen(url) as r:
        data = r.read()
    with open(dest, "wb") as f:
        f.write(data)


def fetch_agents() -> dict[str, dict]:
    os.makedirs(AGENTS_DIR, exist_ok=True)
    data = get_json(f"{API}/agents?isPlayableCharacter=true")["data"]
    out: dict[str, dict] = {}
    for a in data:
        name = a["displayName"]
        icon = a.get("displayIcon")
        if not icon:
            continue
        s = slug(name)
        dest = os.path.join(AGENTS_DIR, f"{s}.png")
        download(icon, dest)
        out[name] = {
            "slug": s,
            "icon": f"/assets/agents/{s}.png",
            "role": (a.get("role") or {}).get("displayName", ""),
        }
        print(f"agent {name:14s} -> {dest}")
    return out


def fetch_ranks() -> dict[str, dict]:
    os.makedirs(RANKS_DIR, exist_ok=True)
    episodes = get_json(f"{API}/competitivetiers")["data"]
    tiers = episodes[-1]["tiers"]  # latest tier set
    out: dict[str, dict] = {}
    for t in tiers:
        name = t["tierName"].title()  # "GOLD 2" -> "Gold 2"
        icon = t.get("smallIcon")
        if not icon or name.lower() == "unrated" or name.lower() == "unranked":
            # still keep unranked icon if present
            if not icon:
                continue
        s = slug(name)
        dest = os.path.join(RANKS_DIR, f"{s}.png")
        download(icon, dest)
        out[name] = {"slug": s, "icon": f"/assets/ranks/{s}.png"}
        print(f"rank  {name:14s} -> {dest}")
    return out


def write_manifest(agents: dict, ranks: dict) -> None:
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    header = (
        "// AUTO-GENERATED by scripts/fetch_valorant_assets.py — do not edit by hand.\n"
        "// Maps Valorant agent / rank names to downloaded asset paths under /public/assets.\n\n"
    )
    body = (
        f"export const AGENT_ASSETS: Record<string, {{ slug: string; icon: string; role: string }}> = {json.dumps(agents, indent=2)} as const\n\n"
        f"export const RANK_ASSETS: Record<string, {{ slug: string; icon: string }}> = {json.dumps(ranks, indent=2)} as const\n"
    )
    with open(MANIFEST, "w") as f:
        f.write(header + body)
    print(f"manifest -> {MANIFEST} ({len(agents)} agents, {len(ranks)} ranks)")


def main() -> None:
    agents = fetch_agents()
    ranks = fetch_ranks()
    write_manifest(agents, ranks)


if __name__ == "__main__":
    main()
